### ISSUE TITLE
multiline formatting seems to be failing

### ISSUE THREAD

**Issue by karolyi** [eivindfjeldstad/textarea-editor#1] opened 2017-02-02 19:23 UTC
hey,

did you try this plugin in an actual browser with a textarea? I see your test only use nodejs.

for me, the multiline formatting fails. here, an example:
before:

![image](https://cloud.githubusercontent.com/assets/987055/22564577/52dfa058-e985-11e6-8820-4ac841675ac9.png)

after:
![image](https://cloud.githubusercontent.com/assets/987055/22564600/68c09ec2-e985-11e6-8097-c926473ac8a1.png)

it totally screws up the selected text.

**Comment by eivindfjeldstad** [comment] 2017-02-02 20:52
Hmm, that's weird. What OS and browser are you using? What listeners are you attaching to the toolbar buttons?

**Comment by karolyi** [comment] 2017-02-02 20:57
the listeners are click listeners on buttons

chrome canary on windows 10.

**Comment by eivindfjeldstad** [comment] 2017-02-02 21:00
I think I know why this might be happening. If you change https://github.com/eivindfjeldstad/textarea-editor/blob/master/index.js#L418
to
```js
return str.replace('\n\r', '\n');
```
does that fix the problem?

**Comment by karolyi** [comment] 2017-02-02 21:04
nope, same effect.

**Comment by eivindfjeldstad** [comment] 2017-02-02 21:09
Are you calling `.preventDefault()` on mousedown like [this](https://github.com/eivindfjeldstad/textarea-editor/blob/master/example/index.js#L7)? What if you replace the line I mentioned peviously with

```js
return str.replace('\r', '');
```
?

**Comment by karolyi** [comment] 2017-02-02 21:11
here's the full code, nothing extensively difficult:

```javascript
/* globals gettext */
import $ from 'jquery'
import 'bootstrap/js/src/tooltip'
import 'bootstrap/js/src/tab'
import TextareaEditor, { formats as editorFormats } from 'textarea-editor'
import marked from 'marked'
import template from './template/rich-text-area.html'

editorFormats.strikethrough = {
  prefix: '~~',
  suffix: '~~',
}
editorFormats.forumEmbed = {
  block: true,
  prefix: '[EMBED:',
  suffix: ']',
}

const anyCharRegex = /^\S+$/i

marked.setOptions({
  sanitize: true,
  breaks: true,
})

// import * as URI from 'urijs'
// import * as common from './common'

// const cachedResponses = {
//   'www.stuff.com': '<b>wwwstuffreplacedtext</b>',
// }

// const paginator = require('./paginator')
// const userName = require('./userName')
// const timeActualizer = require('./timeActualizer')
// const popOverHoverContent = require('./popOverHoverContent')

export class Instance {
  constructor(options) {
    this.options = options
  }

  onClickTab(event) {
    const jqElement = $(event.target)
    event.preventDefault()
    jqElement.tab('show')
    if (!jqElement.is('.tab-preview')) return
    // Preview is clicked, update content
    this.updatePreview()
  }

  onPaste(event) {
    this.isPasteHappened = true
  }

  onInput(event) {
    if (this.isPasteHappened) {
      this.isPasteHappened = false
      return
    }
  }

  onClickToolbarBold() {
    this.editor.toggle('bold')
  }

  onClickToolbarItalic() {
    this.editor.toggle('italic')
  }

  onClickToolbarStrikethrough() {
    this.editor.toggle('strikethrough')
  }

  onClickToolbarUl() {
    this.editor.toggle('unorderedList')
  }

  onClickToolbarOl() {
    this.editor.toggle('unorderedList')
  }

  onClickToolbarQuote() {
    this.editor.toggle('blockquote')
  }

  onClickToolbarH1() {
    this.editor.toggle('header1')
    // this.editor.toggle('header1')
  }

  onClickToolbarH2() {
    this.editor.toggle('header2')
  }

  onClickToolbarH3() {
    this.editor.toggle('header3')
  }

  onClickToolbarEmbed() {
    // this.insertFormattingBeforeAfter('[EMBED:', ']', true)
    this.editor.toggle('forumEmbed')
  }

  insertFormattingBeforeAfter(prefix, suffix, newParagraph = false) {
    this.options.jqElement.focus()
    const text = this.options.jqElement.val()
    const selectionStart = this.options.jqElement.prop('selectionStart')
    const selectionEnd = this.options.jqElement.prop('selectionEnd')
    const selectionBefore = text.slice(0, selectionStart)
    const selection = text.slice(selectionStart, selectionEnd)
    if (selection.indexOf('\n') !== -1) {
      // Don't add formatting when multiple lines detected
      return
    }
    const selectionAfter = text.slice(selectionEnd, text.length)
    let formatPrefix = prefix
    let formatSuffix = suffix
    let newLines
    if (newParagraph) {
      // This element has to be put into a new paragraph
      const twoCharsBefore = text.slice(selectionStart - 2, selectionStart)
      const twoCharsAfter = text.slice(selectionEnd, selectionEnd + 2)
      if (anyCharRegex.test(twoCharsBefore)) {
        // Add new lines before the element
        newLines = twoCharsBefore[1] === '\n' ? '\n' : '\n\n'
        formatPrefix = `${newLines}${prefix}`
      }
      if (anyCharRegex.test(twoCharsAfter)) {
        // Add new lines after the element
        newLines = twoCharsAfter[0] === '\n' ? '\n' : '\n\n'
        formatSuffix = `${suffix}${newLines}`
      }
    }
    const newValue =
      `${selectionBefore}${formatPrefix}${selection}` +
      `${formatSuffix}${selectionAfter}`
    this.options.jqElement.val(newValue)
    this.options.jqElement
      .prop('selectionStart', selectionStart + formatPrefix.length)
      .prop('selectionEnd', selectionEnd + formatPrefix.length)
      .focus()
  }

  updatePreview() {
    const fieldValue = this.options.jqElement.val()
    const htmlContent = marked(fieldValue)
    this.jqPreviewWrapper.html(htmlContent)
  }

  initBtnToolbar() {
    const jqToolbar = this.jqTemplate.find('.btn-toolbar')
    jqToolbar.find('.toolbar-bold')
      .prop('title', gettext('Insert bold formatting'))
      .click(::this.onClickToolbarBold)
    jqToolbar.find('.toolbar-italic')
      .prop('title', gettext('Insert italic formatting'))
      .click(::this.onClickToolbarItalic)
    jqToolbar.find('.toolbar-strikethrough')
      .prop('title', gettext('Insert strikethrough formatting'))
      .click(::this.onClickToolbarStrikethrough)
    jqToolbar.find('.toolbar-ul')
      .prop('title', gettext('Insert unordered list formatting'))
      .click(::this.onClickToolbarUl)
    jqToolbar.find('.toolbar-ol')
      .prop('title', gettext('Insert ordered list formatting'))
      .click(::this.onClickToolbarOl)
    jqToolbar.find('.toolbar-quote')
      .prop('title', gettext('Insert quote formatting'))
      .click(::this.onClickToolbarQuote)
    jqToolbar.find('.toolbar-h1')
      .prop('title', gettext('Insert heading 1 formatting'))
      .click(::this.onClickToolbarH1)
    jqToolbar.find('.toolbar-h2')
      .prop('title', gettext('Insert heading 2 formatting'))
      .click(::this.onClickToolbarH2)
    jqToolbar.find('.toolbar-h3')
      .prop('title', gettext('Insert heading 3 formatting'))
      .click(::this.onClickToolbarH3)
    jqToolbar.find('.toolbar-embed')
      .prop('title', gettext('Embed video/link/image'))
      .click(::this.onClickToolbarEmbed)
    jqToolbar.find('[data-toggle=tooltip]').tooltip()
  }

  initialize() {
    this.jqTemplate = $(template)
    this.jqPreviewWrapper = this.jqTemplate.find('.tabpane-preview')
    this.id = this.options.jqElement.attr('id')
    // Setup tabs
    this.jqTemplate.find('.tab-edit')
      .prop('href', `#tabpane_edit_${this.id}`)
      .attr('aria-controls', `tabpane_edit_${this.id}`)
      .text(gettext('Edit'))
    this.jqTemplate.find('.tab-preview')
      .prop('href', `#tabpane_preview_${this.id}`)
      .attr('aria-controls', `tabpane_preview_${this.id}`)
      .text(gettext('Preview'))
    // Setup tabpanes
    this.jqTemplate.find('.tabpane-edit')
      .prop('id', `tabpane_edit_${this.id}`)
    this.jqTemplate.find('.tabpane-edit .textarea-wrapper')
      .append(this.options.jqElement)
    this.jqTemplate.find('.tabpane-preview')
      .prop('id', `tabpane_preview_${this.id}`)
    this.jqTemplate.find('a').click(::this.onClickTab)
    this.options.jqElement
      .on('paste', ::this.onPaste)
      .on('input', ::this.onInput)
    this.editor = new TextareaEditor(this.options.jqElement[0])
    this.initBtnToolbar()
    this.options.jqWrapper.append(this.jqTemplate)
  }
}

export function init(options) {
  const richMdTextArea = new Instance(options)
  richMdTextArea.initialize()
  return richMdTextArea
}
```

**Comment by karolyi** [comment] 2017-02-02 21:13
also I'm live on http://livecoding.edu/karolyi, you can join me there

**Comment by eivindfjeldstad** [comment] 2017-02-02 21:21
Might be because the selection is losing focus when the toolbar buttons are clicked. You should prevent default on `mousedown` for the toolbar element.

**Comment by karolyi** [comment] 2017-02-02 21:23
assuming it loses the selection? In this code I pasted, there's a function I implemented with the name `insertFormattingBeforeAfter`, does more or less the same, is wired in the same way, and works.

I'm sure it's not on the selection and focus loss.

**Comment by eivindfjeldstad** [comment] 2017-02-03 00:35
I haven't managed to reproduce this. When you click on the toolbar, does the text remain selected or does the selection collapse? As I said before, my guess is that the selection collapses because you don't prevent default on mousedown. That's why only the first line is formatted, and also why single line formatting works fine. Looking at your screenshots, that's exactly how it would look. There's not much more I can do without a failing test case or more specifics.

**Comment by karolyi** [comment] 2017-02-03 00:36
Thx!

I'll test your hypothesis and create a test case tomorrow.

**Comment by karolyi** [comment] 2017-02-07 16:15
I just tested it, the assumption is false.

I selected the text in the editor, went to devtools, selected a certain amount of text, and then run `editor.toggle('unorderedList')` on it.

I put some debug to line 245 to see if the `before`, `content` and `after` gets the right value. The debug has shown they got the right values. Then, the formatting still failed with the same result.

**Comment by karolyi** [comment] 2017-02-19 14:06
bump

**Comment by eivindfjeldstad** [comment] 2017-02-20 09:12
Hmm. It's really hard to know whats going on without a test case. Can you get the example to run? Just run `npm start`

**Comment by eivindfjeldstad** [comment] 2018-04-04 00:59
I'm closing this. Please let me know if it's still a problem

**Closed by eivindfjeldstad** 2018-04-04 00:59 UTC

**Comment by karolyi** [comment] 2018-04-04 10:41
I'm working on another project right now, which takes all my time so cannot really test. Leave this closed, and I'll open another one if it's still relevant by the time I'll be able to get back to this.

Cheers
